### PR TITLE
ADR-003 Storing LCP Passphrase for Offline Reading

### PR DESCRIPTION
**Pull request by jonathangreen**
> 🚧 Under construction.

Moving draft of ADR-003 from Notion to github.

### CODE REVIEW

**Comment by jonathangreen** [comment]
@vladimirfedorov Can you fill in the iOS section in this document?

**Comment by vladimirfedorov** [comment]
> @vladimirfedorov Can you fill in the iOS section in this document?

@jonathangreen sure, will do

**Comment by mauricecarrier7** [comment]
iOS looks good to me.

**Review by mauricecarrier7 — APPROVED** [review]

**Comment by ray-lee** [comment]
Looks good to me too.

**Pull request merged**
